accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import register, auth_view, lk_view, upload_avatar, create_like



urlpatterns = [
    path('lk/', lk_view, name='lk'),
    path('registration/', register, name='registration'),
    path('auth/', auth_view, name='auth'),
    path('upload-avatar/', upload_avatar, name='upload_avatar'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('accounts/login/', auth_view, name='login'),
    path('like/<int:pk>/', create_like, name='like'),
]

content_manager/urls.py
from django.urls import path

from .views import create_dish_drf, create_dish_form, view_dishes, dish_edit


app_name = 'content_manager'

urlpatterns = [
    path('create_dish_drf/', create_dish_drf, name='create_dish_drf'),
    path('create_dish_form/', create_dish_form, name='create_dish_form'),
    path('dishes/', view_dishes, name='dishes'),
    path('dish/<int:pk>/edit/', dish_edit, name='dish_edit'),
]

foodplan/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from recipeapp.views import (
    recipe_view,
    index_view,
    order_view,
    all_recipes_view,
    day_menu_view,
    cheap_recipes_view,
    liked_recipes_view,
    show_default_recipe,
)


Dish = apps.get_model('recipeapp', 'Dish')
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('recipe/<int:recipe_id>', recipe_view, name='recipe'),
    path('default_recipe/', show_default_recipe,  name='recipe_default'),  
    path('', index_view, name='index'),
    path('order/', order_view, name='order'),
    path('all_recipes/', all_recipes_view, name='all_recipes'),
    path('cheap_recipes/', cheap_recipes_view, name='cheap_recipes'),
    path('liked_recipes/', liked_recipes_view, name='liked_recipes'),
    path('day_menu/', day_menu_view, name='day_menu'),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('content_manager.urls', 'content_manager'), namespace='content_manager')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/auth.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Foodplan 2021 - Меню на неделю FOODPLAN{% endblock %}
{% block content %}
<section>
    <div class="container">
        <div class="card p-3 mb-5 foodplan__shadow">
            <a href="#" class="link-secondary fw-light foodplan__backButton">
                <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                     viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                </svg>
            </a>
            <h2 class="text-center"><strong>Авторизация</strong></h2>
        </div>
        <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
            <form method="post" action="{% url 'accounts:auth' %}">
                {% csrf_token %}
                <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" required>
                </div>
                <div class="mb-3">
                    <div class="d-flex align-items-center justify-content-between">
                        <label for="password" class="form-label">Пароль</label>
                        <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>
                    </div>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="row mb-3">
                    <div class="col-12 col-sm-6 mt-3">
                        <button type="submit" class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                    </div>
                    <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                        <small>Нет аккаунта? <a href="{% url 'accounts:registration' %}" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}План питания на неделю, меню, рецепты, список покупок{% endblock %}</title>
</head>
<body>
    {% include 'header.html' %}
    
    <main style="margin-top: calc(2rem + 85px);">
        {% block content %}
        {% endblock %}
    </main>

    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/create_dish.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создать блюдо с ингредиентами</title>
</head>
<body>
    <h1>Создать новое блюдо с ингредиентами</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Блюдо</h2>
        {{ dish_form.as_p }}
        
        <h2>Ингредиенты</h2>
        {{ items_formset.management_form }}
        {% for form in items_formset %}
            {{ form.as_p }}
        {% endfor %}
        
        <button type="submit">Сохранить блюдо</button>
    </form>
</body>
</html>

templates/day_menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню{% endblock %}
{% block content %}
<div class="container">
  <center>
    <h2>Меню на день</h2>
  </center>
  <hr/>
  <table class="table table-responsive" id="menu-table">
    <thead>
        <tr>
            <th>Завтрак</th>
            <th>Обед</th>
            <th>Ужин</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for menu in menus %}
            <th>
                <a href="{% url 'recipe' menu.breakfast.id %}" class="black-title">{{ menu.breakfast.title }}</a>
                <br>
                <img src="{{ menu.breakfast.img.url }}" style="max-width: 50%">
            </th>
            <th>
                <a href="{% url 'recipe' menu.lunch.id %}" class="black-title">{{ menu.lunch.title }}</a>
                <br>
                <img src="{{ menu.lunch.img.url }}" style="max-width: 50%">
            </th>
            <th>
                <a href="{% url 'recipe' menu.dinner.id %}" class="black-title">{{ menu.dinner.title }}</a>
                <br>
                <img src="{{ menu.dinner.img.url }}" style="max-width: 50%">
            </th>
            {% endfor %}
        </tr>
    </tbody>
</table>
</div>
{% endblock %}

templates/dish_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Редактировать блюдо</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <h2>Ингредиенты</h2>
        {{ items_formset.management_form }}
        {% for form in items_formset %}
            {{ form.as_p }}
        {% endfor %}
        
        <button type="submit">Сохранить блюдо</button>
    <button type="submit">Сохранить изменения</button>
</form>

<a href="{% url 'content_manager:dishes' %}">Отмена</a>
{% endblock %}

templates/dishes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <center>
    <h2>Блюда</h2>
  </center>
  <hr/>
  <br/>
  <br/>
  <div class="container">
    <table class="table table-responsive">
     <tr>
       <th>ID блюда</th>
       <th>Название</th>
       <th>Изображение</th>
       <th>Описание</th>
       <th>Инструкция</th>
       <th>Категория</th>
       <th>Активно?</th>
       <th>Ссылка на админку</th>
       <th>Редактировать</th>
     </tr>
 
     {% for dish in dishes %}
     <tr>
      <td>{{ dish.id }}</td>
      <td>{{ dish.title }}</td>
      <td><img src="{{ dish.img.url }}" alt="{{ dish.title }}" style="max-width: 100px; max-height: 100px;"></td>
      <td>{{ dish.description }} руб.</td>
      <td>{{ dish.instruction}} {{ order.lastname }}</td>
      <td>{{ dish.category }}</td>
      <td>
        {% if dish.is_active %}
            &#10003; <!-- Галочка -->
        {% else %}
            &#10007; <!-- Крестик -->
        {% endif %}
    </td>
      <td><a href="{% url 'admin:recipeapp_dish_change' object_id=dish.id %}?next={{ request.get_full_path|urlencode }}">Админка</a></td>
      <td><a href="{% url 'content_manager:dish_edit' dish.id %}">Редактировать</a></td>
     </tr>
    {% endfor %}
    </table>
    <td><a href="{% url 'content_manager:create_dish_form' %}">Добавить новое блюдо</a></td>
 </div>
 {% endblock %}

templates/footer.html
{% load static %}
<footer class="footer py-4 mt-5" style="border-top: 1px solid lightgray;">
    <div class="container d-flex flex-row justify-content-between mb-2">
        <a href="https://vk.com/devmanorg">
            <img src="{% static 'img/vk.png' %}" height="40" width="auto" alt="">
        </a>
        <div>
            <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Виды меню</b></a>
            <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Блог</b></a>
            <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Контакты</b></a>
        </div>
    </div>
    <div class="container">
        <h6 class="link-secondary text-center"><a href="#" class="link-secondary me-2">Политика конфиденциальности</a><a href="#" class="link-secondary">Пользовательское соглашение</a></h6>
        <h6 class="link-secondary text-center">© Devman 2022. All right reserved.</h6>
    </div>
</footer>

templates/header.html
{%load static %}
<header id="header">
    <nav class="navbar navbar-light fixed-top navbar__opacity">
        <div class="container">
            <a href="{% url 'index' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Главная</a>
            <a href="{% url 'accounts:lk' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Личный кабинет</a>
            <a class="navbar-brand" href="https://dvmn.org/">
                <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
            </a>
            {% if user.is_staff %}
            <a href="{% url 'content_manager:dishes' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Редактирование блюд</a>
            {% endif %}
            {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Выйти</button>
            </form>
            {% else %}
              <a href="{% url 'accounts:auth' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Войти</a>
            {% endif %}
        </div>
    </nav>
</header>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная страница - План питания{% endblock %}
{% block content %}
  <section class="foodplan__head_bg">
      <div class="container">
          <div class="d-flex w-50 py-lg-5 foodplan__head">
              <div class="d-flex flex-column justify-content-start foodplan__head_desc">
                  <h1 class="mb-5"><b>Вдохновляем готовить дома!</b></h1>
                  <h4>Мы планируем домашнее меню.<br>
                      Вы получаете рецепты + список продуктов.<br>
                      Больше не нужно думать, что готовить.</h4>
                  <div class="d-block mt-3">
                    <a href="{% url 'recipe_default' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Хочу попробовать</a>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section>
      <div class="container my-5">
          <div class="row d-flex justify-content-center">
              <div class="col-sm-6 col-lg-3">
                  <div class="card mb-1 foodplan__card_borderless">
                      <img src="{% static 'img/circle1.png' %}" class="card-img-top" alt="">
                      <div class="card-body">
                          <h5 class="card-title"><b>Меню на неделю</b></h5>
                          <p class="card-text">Итальянская паста, котлеты с пюре или овощное карри - решать вам!
                          Подстраивайте меню под свои желания.</p>
                      </div>
                  </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                  <div class="card mb-1 foodplan__card_borderless">
                      <img src="{% static 'img/circle2.png' %}" class="card-img-top" alt="">
                      <div class="card-body">
                          <h5 class="card-title"><b>Удобный список продуктов</b></h5>
                          <p class="card-text">С четким списком вы не возьмете лишнего, будете тратить меньше и сможете чаще покупать лосось и морепродукты.</p>
                      </div>
                  </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                  <div class="card mb-1 foodplan__card_borderless">
                      <img src="{% static 'img/circle3.png' %}" class="card-img-top" alt="">
                      <div class="card-body">
                          <h5 class="card-title"><b>Доставка от ВкусВилл</b></h5>
                          <p class="card-text">Заказывайте доставку продуктов по вашему списку в 1 клик. Все ингредиенты попадут в корзину ВкусВилл автоматически.</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section>
      <div class="container my-5">
          <h1 class="text-center my-4"><b>В каждом меню только хиты</b></h1>
          <div class="container w-md-75">
              <div id="carousel1" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                      <div class="carousel-item active">
                          <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="...">
                          <div class="card-img-overlay text-white text-center carousel-item__gradient">
                              <h5><b>Модный и полезный ужин</b></h5>
                              <h2><b>Боул с креветками и рисом</b></h2>
                          </div>
                      </div>
                      <div class="carousel-item">
                          <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="...">
                          <div class="card-img-overlay text-white text-center carousel-item__gradient">
                              <h5><b>Интересно, просто и супер вкусно</b></h5>
                              <h2><b>Тосканский суп с фаршем</b></h2>
                          </div>
                      </div>
                      <div class="carousel-item">
                          <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="...">
                          <div class="card-img-overlay text-white text-center carousel-item__gradient">
                              <h5><b>Понятное всей семье, яркое на вкус</b></h5>
                              <h2><b>Паприкаш с курицей</b></h2>
                          </div>
                      </div>
                      <div class="carousel-item">
                          <img src="{% static 'img/4.jpg' %}" class="d-block w-100" alt="...">
                          <div class="card-img-overlay text-white text-center carousel-item__gradient">
                              <h5></h5><b>Летнее удовольствие</b></h5>
                              <h2><b>Овощной салат с жареным халуми</b></h2>
                          </div>
                      </div>
                      <div class="carousel-item">
                          <img src="https://foodplan.ru/local/images-for-pages/landing/img/cards/5.jpg" class="d-block w-100"
                              alt="...">
                          <div class="card-img-overlay text-white text-center carousel-item__gradient">
                              <h5><b>Который все пекут повторно</b></h5>
                              <h2><b>Брауни чизкейк с ягодами</b></h2>
                          </div>
                      </div>
                  </div>
                  <button class="carousel-control-prev carousel__button_prev" type="button" data-bs-target="#carousel1"
                      data-bs-slide="prev">
                      <span class="foodplan_green" aria-hidden="true">
                          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-left-circle carousel__svg_prev"
                              viewBox="0 0 16 16">
                              <path fill-rule="evenodd"
                                  d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                          </svg>
                      </span>
                      <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next carousel__button_next" type="button" data-bs-target="#carousel1"
                      data-bs-slide="next">
                      <span class="foodplan_green" aria-hidden="true">
                          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-right-circle carousel__svg_next"
                              viewBox="0 0 16 16">
                              <path fill-rule="evenodd"
                                  d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z" />
                          </svg>
                      </span>
                      <span class="visually-hidden">Next</span>
                  </button>
              </div>
          </div>
          
      </div>
  </section>
  <section>
      <div class="container my-5">
          <div class="container w-md-75 foodplan__mobapp">
              <div class="d-flex w-md-50 flex-column align-items-center justify-content-between foodplan__mobapp_desc">
                  <h1 class="py-5"><b>Пользуйтесь, как вам удобно</b></h1>
                  <h4>Открывайте меню в мобильном приложении, на компьютере, планшете, или распечатывайте на принтере.</h4>
                  <h4>Создавайте свою личную коллекцию избранных рецептов.</h4>
                  <div class="d-block py-5">
                      <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green me-2 mb-2">Загрузите в App
                          Store</button>
                      <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green me-2 mb-2">Загрузите в Google
                          Play</button>
                  </div>
              </div>
          </div>
          
      </div>
  </section>
  <section>
      <div class="container mb-5">
          <div class="row">
              <div class="col-12 col-sm-4">
                  <div class="foodplan__creator pounded-pill" style="height: 300px;"></div>
                  <h5 class="text-center">Марина Амельченко</h5>
                  <h6 class="text-center">Основатель Foodplan</h6>
              </div>
              <div class="col-12 col-sm-8">
                  <h1 class="mb-4">,,</h1>
                  <h4>Каждую неделю мы создаем меню с любовью и заботой. Поэтому нам доверяют более 30 000 семей.</h4>
                  <h4>Начните путешествие в мир новых вкусов с нами.</h4>
                  <h1 style="text-align: end;">,,</h1>
              </div>
          </div>
      </div>
  </section>
  <section>
      <div class="container mb-5">
          <h1 class="mb-3 text-center"><strong>Истории наших пользователей</strong></h1>
          <div class="row">
              <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                  <img src="{% static 'img/IMG_1899.jpg' %}" alt="" class="foodplan__story">
              </div>
              <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                  <img src="{% static 'img/IMG_1900.jpg' %}" alt="" class="foodplan__story">
              </div>
              <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                  <img src="{% static 'img/IMG_1901.jpg' %}" alt="" class="foodplan__story">
              </div>
              <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                  <img src="{% static 'img/IMG_1902.jpg' %}" alt="" class="foodplan__story">
              </div>
          </div>
      </div>
  </section>
  <section>
      <div class="container mb-5">
          <div class="row d-flex justify-content-center">
              <div class="col-12 col-sm-6 col-lg-4">
                  <div class="d-flex flex-row justify-content-between m-1">
                      <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                      <div class="d-flex flex-column align-items-center text-center justify-content-center">
                          <h5>Выпускник Сбербанк 500 Startups</h5>
                          <h5>Moscow</h5>
                      </div>
                      <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                  </div>
              </div>
              <div class="col-12 col-sm-6 col-lg-4">
                  <div class="d-flex flex-row justify-content-between m-1">
                      <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                      <div class="d-flex flex-column align-items-center text-center justify-content-center">
                          <h5>Диплом повара Le Cordon Bleu</h5>
                          <h5>London</h5>
                      </div>
                      <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                  </div>
              </div>
              <div class="col-12 col-sm-6 col-lg-4">
                  <div class="d-flex flex-row justify-content-between m-1">
                      <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                      <div class="d-flex flex-column align-items-center text-center justify-content-center">
                          <h5>При поддержке Austrian Angel Investors</h5>
                          <h5>Vienna</h5>
                      </div>
                      <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                  </div>
              </div>
          </div>
      </div>
  </section>
{% endblock %}

templates/lk.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Foodplan 2021 - Меню на неделю FOODPLAN{% endblock %}
{% block content %}
        <section>
            <div class="container">
                <div class="row">
                    <div class="card col-12 p-3 mb-5 foodplan__shadow">
                        <h4 class="foodplan__backButton">
                            <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
                        </h4>
                        <h2 class="text-center"><strong>Личный кабинет</strong></h2>
                    </div>
                    
                    <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
                        <div class="position-relative">
                            {% if user.avatar %}
                              <img src="{{ user.avatar.url }}" alt="" width="100" height="100" class="rounded-pill">
                            {% else %}
                              <img src="{% static 'img/test_avatar.png' %}" alt="" width="100" height="100" class="rounded-pill">
                            {% endif %}
                            <span class="badge rounded-circle position-absolute bottom-0 end-0 foodplan__bg_green avatar__plus"><a href="{% url 'accounts:upload_avatar' %}"
                                    class="link-dark text-decoration-none align-middle">+</a></span>
                        </div>
                        <h3 class="card-title text-center">{{ name }}</h3>
                        <h7 class="card-title text-center">{{ email }}</h7>
                        <div class="d-block">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Выйти</button>
                        </div>
                    </div>

                    <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
                        <ul class="nav nav-tabs">
                            <li class="nav-item foodplan__tab-item">
                                <button id="tab2" class="btn shadow-none foodplan__tab-button active" data-bs-toggle="tab" data-bs-target="#menu">Моё меню</button>
                            </li>
                            <li class="nav-item foodplan__tab-item">
                                <button id="tab1" class="btn shadow-none foodplan__tab-button" data-bs-toggle="tab" data-bs-target="#data">Персональные данные</button>
                            </li>
                            <li class="nav-item foodplan__tab-item flex-grow-1"></li>
                        </ul>
                        <div class="tab-content mt-2">
                            <div class="tab-pane fade show active" id="menu">
                                <div class="row">
                                    <div class="col-2">
                                        <img src="{% static 'img/circle1.png' %}" alt="" class="w-100">
                                    </div>
                                    <div class="col-10 col-md-10">
                                        <div class="row">
                                            <div class="col-12">
                                                <a href="{% url 'day_menu' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Меню дня</a>
                                            </div>
                                            <br />
                                            <br />
                                            <div class="col-12">
                                                <a href="{% url 'all_recipes' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Посмотреть все рецепты</a>
                                            </div>
                                            <br />
                                            <br />
                                            <div class="col-12">
                                                <a href="{% url 'cheap_recipes' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Хочу сэкономить!</a>
                                            </div>
                                            <br />
                                            <br />   
                                            <div class="col-12">
                                                <a href="{% url 'liked_recipes' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Избранное</a>   
                                            </div>  
                                        </div> 
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="data">
                                <form action="">
                                    <div class="mb-3">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <label for="exampleInputEmail1" class="form-label">Имя</label>
                                            <small><a href="#" class="link-dark foodplan_green">изменить</a></small>
                                        </div>
                                        <input type="text" class="form-control" id="name">
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleInputEmail1" class="form-label">Email</label>
                                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp">
                                    </div>
                                    <div class="mb-3">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <label for="exampleInputPassword1" class="form-label">Пароль</label>
                                            <small><a href="#" class="link-dark foodplan_green">изменить</a></small>
                                        </div>
                                        <input type="password" class="form-control" id="password">
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleInputPassword1" class="form-label">Подтверждение пароля</label>
                                        <input type="password" class="form-control" id="PasswordConfirm">
                                    </div>
                                    <div class="d-block">
                                        <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Сохранить изменения</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}